# Generated by Django 4.1.3 on 2022-12-11 21:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import winds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WindGenParams",
            fields=[
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_windless", models.BooleanField(default=False)),
                ("is_constant", models.BooleanField(default=False)),
                ("is_oscillatory", models.BooleanField(default=False)),
                ("is_lorenz", models.BooleanField(default=False)),
                (
                    "base_velocity",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=winds.models.get_triple_0,
                        max_length=3,
                        size=None,
                    ),
                ),
                (
                    "frequency",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=winds.models.get_triple_0,
                        max_length=3,
                        size=None,
                    ),
                ),
                (
                    "amplitude",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=winds.models.get_triple_0,
                        max_length=3,
                        size=None,
                    ),
                ),
                (
                    "phase_offset",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=winds.models.get_triple_0,
                        max_length=3,
                        size=None,
                    ),
                ),
                ("rho", models.FloatField(default=0, null=True)),
                ("sigma", models.FloatField(default=0, null=True)),
                ("beta", models.FloatField(default=0, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WindSpacetime",
            fields=[
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generator_name",
                    models.CharField(
                        choices=[
                            ("windless", "windless"),
                            ("constant", "constant"),
                            ("oscillatory", "oscillatory"),
                            ("lorenz", "lorenz"),
                        ],
                        max_length=30,
                    ),
                ),
                ("duration", models.FloatField(default=100)),
                ("timestep", models.FloatField(default=0.01)),
                ("blob_filename", models.CharField(max_length=50, null=True)),
                (
                    "generator_parameters",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="winds.windgenparams",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
