# Generated by Django 4.1.3 on 2022-12-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("winds", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="windspacetime",
            old_name="generator_parameters",
            new_name="generator_params",
        ),
    ]
