# Generated by Django 4.1.3 on 2022-12-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("winds", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="windgeneratorparameters",
            old_name="base_speed",
            new_name="base_velocity",
        ),
    ]
