# Generated by Django 4.1.3 on 2022-12-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("winds", "0002_alter_windspacetime_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windspacetime",
            name="generator_parameters",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="winds.windgeneratorparameters",
            ),
        ),
    ]
