# Generated by Django 4.1.3 on 2022-12-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winds", "0003_alter_windspacetime_generator_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windgeneratorparameters",
            name="is_constant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="windgeneratorparameters",
            name="is_lorenz",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="windgeneratorparameters",
            name="is_oscillatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="windgeneratorparameters",
            name="is_windless",
            field=models.BooleanField(default=False),
        ),
    ]
