# Generated by Django 4.1.3 on 2022-12-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("g", models.FloatField()),
                ("max_initial_speed", models.FloatField()),
                ("max_wait_time", models.FloatField()),
                ("prob_timing_center", models.FloatField()),
                ("prob_timing_spread", models.FloatField()),
                (
                    "prob_aiming_function",
                    models.CharField(
                        choices=[
                            ("EulerAngles", "EulerAngles"),
                            ("SphericalCoordinates", "SphericalCoordinates"),
                            ("CylindricalCoordinates", "CylindricalCoordinates"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prob_aiming_X1_center", models.FloatField()),
                ("prob_aiming_X1_spread", models.FloatField()),
                ("prob_aiming_X2_center", models.FloatField()),
                ("prob_aiming_X2_spread", models.FloatField()),
                ("prob_aiming_X3_center", models.FloatField()),
                ("prob_aiming_X3_spread", models.FloatField()),
                ("timestep", models.FloatField()),
                ("blob_filename", models.CharField(max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("g", models.FloatField()),
                ("max_initial_speed", models.FloatField()),
                ("max_wait_time", models.FloatField()),
                ("prob_timing_center", models.FloatField()),
                ("prob_timing_spread", models.FloatField()),
                (
                    "prob_aiming_function",
                    models.CharField(
                        choices=[
                            ("EulerAngles", "EulerAngles"),
                            ("SphericalCoordinates", "SphericalCoordinates"),
                            ("CylindricalCoordinates", "CylindricalCoordinates"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prob_aiming_X1_center", models.FloatField()),
                ("prob_aiming_X1_spread", models.FloatField()),
                ("prob_aiming_X2_center", models.FloatField()),
                ("prob_aiming_X2_spread", models.FloatField()),
                ("prob_aiming_X3_center", models.FloatField()),
                ("prob_aiming_X3_spread", models.FloatField()),
                ("timestep", models.FloatField()),
                ("simtrials", models.ManyToManyField(to="simulator.simtrial")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
