# Generated by Django 4.1.3 on 2022-12-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("winds", "0001_initial"),
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simexperiment",
            name="windgenparams",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="winds.windgenparams",
            ),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="windspacetime",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="winds.windspacetime",
            ),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="windgenparams",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="winds.windgenparams",
            ),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="windspacetime",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="winds.windspacetime",
            ),
        ),
    ]
