# Generated by Django 4.1.3 on 2022-12-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simexperiment",
            old_name="prob_aiming_function",
            new_name="prob_aiming_geometry",
        ),
        migrations.RenameField(
            model_name="simtrial",
            old_name="prob_aiming_function",
            new_name="prob_aiming_geometry",
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="drag_coef",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="is_control",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="m",
            field=models.FloatField(default=0.0456),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_X1_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_X1_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_X2_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_X2_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_X3_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_X3_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_aiming_fn_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Normal", "Normal"),
                    ("Log-normal", "Log-normal"),
                ],
                default="Uniform",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_speed_center",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_speed_fn_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Normal", "Normal"),
                    ("Log-normal", "Log-normal"),
                ],
                default="Uniform",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_speed_spread",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_timing_fn_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Normal", "Normal"),
                    ("Log-normal", "Log-normal"),
                ],
                default="Uniform",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simtrial",
            name="drag_coef",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="m",
            field=models.FloatField(default=0.0456),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_X1_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_X1_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_X2_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_X2_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_X3_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_X3_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_aiming_fn_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Normal", "Normal"),
                    ("Log-normal", "Log-normal"),
                ],
                default="Uniform",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_speed_center",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_speed_fn_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Normal", "Normal"),
                    ("Log-normal", "Log-normal"),
                ],
                default="Uniform",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_speed_spread",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_timing_fn_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Normal", "Normal"),
                    ("Log-normal", "Log-normal"),
                ],
                default="Uniform",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="g",
            field=models.FloatField(default=-9.81),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="max_initial_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="max_wait_time",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="g",
            field=models.FloatField(default=-9.81),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="max_initial_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="max_wait_time",
            field=models.FloatField(null=True),
        ),
    ]
