# Generated by Django 4.1.3 on 2023-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_simexperiment_num_trials"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simexperiment",
            old_name="max_initial_speed",
            new_name="prob_speed_max",
        ),
        migrations.RenameField(
            model_name="simexperiment",
            old_name="max_wait_time",
            new_name="prob_timing_max",
        ),
        migrations.RenameField(
            model_name="simtrial",
            old_name="max_initial_speed",
            new_name="prob_speed_max",
        ),
        migrations.RenameField(
            model_name="simtrial",
            old_name="max_wait_time",
            new_name="prob_timing_max",
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_speed_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simexperiment",
            name="prob_timing_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_speed_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="simtrial",
            name="prob_timing_min",
            field=models.FloatField(null=True),
        ),
    ]
