# Generated by Django 4.1.3 on 2022-12-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_simexperiment_windgenparams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_aiming_X1_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_aiming_X1_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_aiming_X2_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_aiming_X2_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_aiming_X3_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_aiming_X3_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_speed_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_speed_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_timing_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simexperiment",
            name="prob_timing_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_aiming_X1_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_aiming_X1_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_aiming_X2_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_aiming_X2_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_aiming_X3_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_aiming_X3_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_speed_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_speed_spread",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_timing_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="simtrial",
            name="prob_timing_spread",
            field=models.FloatField(null=True),
        ),
    ]
