# Generated by Django 4.1.3 on 2023-01-14 03:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulator",
            "0003_rename_max_initial_speed_simexperiment_prob_speed_max_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="simtrial",
            name="position_final",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=[0, 0, 0],
                max_length=3,
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simtrial",
            name="position_initial",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=[0, 0, 0],
                max_length=3,
                size=None,
            ),
            preserve_default=False,
        ),
    ]
