# Generated by Django 4.1.3 on 2022-12-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0003_alter_simexperiment_prob_aiming_x1_center_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simtrial",
            old_name="initial_direction",
            new_name="direction_initial",
        ),
        migrations.RenameField(
            model_name="simtrial",
            old_name="initial_speed",
            new_name="speed_initial",
        ),
        migrations.RenameField(
            model_name="simtrial",
            old_name="initial_time",
            new_name="time_initial",
        ),
    ]
